# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 15:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('round_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='#')),
                ('running_time', models.IntegerField(verbose_name='Running Time (ms)')),
                ('running_memory', models.IntegerField(verbose_name='Running Memory (KB)')),
                ('score', models.IntegerField(verbose_name='Gained Score')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('c', 'C++'), ('j', 'Java'), ('p', 'Python')], max_length=1, verbose_name='Language')),
                ('code', models.TextField(verbose_name='Code')),
                ('submit_time', models.DateTimeField(auto_now_add=True, verbose_name='Submit Time')),
                ('compile_result', models.FileField(blank=True, null=True, upload_to='compile/', verbose_name='Compile Result')),
                ('compile_error', models.TextField(blank=True, null=True, verbose_name='Compile Error Message')),
                ('verdict', models.IntegerField(blank=True, choices=[(100, 'Waiting'), (101, 'Running'), (102, 'Pretest Passed (Past)'), (130, 'Compile Error'), (131, 'Compile Finished'), (200, 'Locked'), (201, 'Pretest Passed'), (202, 'Running on Contest'), (400, 'Rejected'), (1000, 'Accepted'), (1001, 'Wrong Answer'), (1002, 'Time Limit Exceeded'), (1003, 'Memory Limit Exceeded'), (1004, 'Runtime Error')], null=True, verbose_name='Verdict')),
                ('running_time', models.IntegerField(blank=True, null=True, verbose_name='Running Time (ms)')),
                ('running_memory', models.IntegerField(blank=True, null=True, verbose_name='Running Memory (KB)')),
                ('score', models.IntegerField(default=0, verbose_name='Score')),
                ('rating', models.IntegerField(default=0, verbose_name='Rating')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.Problem')),
            ],
        ),
        migrations.AddField(
            model_name='run',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.Submission'),
        ),
    ]
