# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running_time', models.IntegerField(verbose_name='Running Time (ms)')),
                ('running_memory', models.IntegerField(verbose_name='Running Memory (KB)')),
                ('score', models.IntegerField(verbose_name='Gained Score')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('c', 'C++'), ('j', 'Java'), ('p', 'Python')], max_length=1, verbose_name='Language')),
                ('code', models.TextField(verbose_name='Code')),
                ('code_length', models.IntegerField(verbose_name='Code Length')),
                ('submit_time', models.DateTimeField(auto_now=True, verbose_name='Submit Time')),
                ('verdict', models.IntegerField(choices=[(100, 'Waiting'), (101, 'Running on Pretest'), (200, 'Locked'), (201, 'Pretest Passed'), (202, 'Running on Contest'), (400, 'Rejected'), (1000, 'Accepted'), (1001, 'Wrong Answer'), (1002, 'Time Limit Exceeded'), (1003, 'Memory Limit Exceeded'), (1004, 'Runtime Error')], verbose_name='Verdict')),
                ('score', models.IntegerField(default=0, verbose_name='Score')),
                ('rating', models.IntegerField(default=0, verbose_name='Rating')),
                ('running_data', models.ManyToManyField(to='submission.Run')),
            ],
        ),
    ]
