# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='running_data',
            field=models.ManyToManyField(related_name='Running', to='submission.Run'),
        ),
    ]
