# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField(verbose_name='Input')),
                ('output', models.TextField(verbose_name='Output')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='Explanation')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='#')),
                ('title', models.CharField(max_length=70, verbose_name='Title')),
                ('submissions', models.IntegerField(default=0, verbose_name='Submissions')),
                ('status', models.CharField(choices=[('r', 'Removed'), ('a', 'Available')], max_length=1, verbose_name='Status')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Likes')),
                ('time_limit', models.IntegerField(default=1000, verbose_name='Time Limit (ms)')),
                ('memory_limit', models.IntegerField(default=512, verbose_name='Memory Limit (MB)')),
                ('program_limit', models.IntegerField(default=128, verbose_name='Program Limit (KB)')),
                ('description', models.TextField(verbose_name='Description')),
                ('input', models.TextField(verbose_name='Input')),
                ('output', models.TextField(verbose_name='Output')),
                ('validator', models.FileField(upload_to='validator/', verbose_name='Validator')),
                ('samples', models.ManyToManyField(related_name='Samples', to='problem.Data')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
