# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='#')),
                ('title', models.CharField(max_length=70, verbose_name='Title')),
                ('submissions', models.IntegerField(default=0, verbose_name='Submissions')),
                ('status', models.CharField(choices=[('r', 'Removed'), ('a', 'Available')], max_length=1, verbose_name='Status')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Likes')),
                ('description', models.TextField(verbose_name='Description')),
                ('input', models.TextField(verbose_name='Input')),
                ('output', models.TextField(verbose_name='Output')),
                ('samples', models.TextField(verbose_name='Samples')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
