# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField(verbose_name='Input')),
                ('output', models.TextField(verbose_name='Output')),
                ('explanation', models.TextField(verbose_name='Explanation')),
            ],
        ),
        migrations.RemoveField(
            model_name='problem',
            name='samples',
        ),
        migrations.AddField(
            model_name='problem',
            name='samples',
            field=models.ManyToManyField(related_name='Samples', to='problem.Data'),
        ),
    ]
