# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_auto_20161221_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='memory_limit',
            field=models.IntegerField(default=1000, verbose_name='Memory Limit (MB)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='program_limit',
            field=models.IntegerField(default=128, verbose_name='Program Limit (KB)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='time_limit',
            field=models.IntegerField(default=512, verbose_name='Time Limit (ms)'),
            preserve_default=False,
        ),
    ]
