# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_auto_20161221_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='memory_limit',
            field=models.IntegerField(default=512, verbose_name='Memory Limit (MB)'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='program_limit',
            field=models.IntegerField(default=128, verbose_name='Program Limit (KB)'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='time_limit',
            field=models.IntegerField(default=1000, verbose_name='Time Limit (ms)'),
        ),
    ]
